language: go

go:
  - 1.10.x

install:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get -u golang.org/x/vgo

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - vgo list -m
  - vgo test -v -race
  - vgo vet -v