[[constraint]]
  name = "github.com/albenik/goerrors"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.7.1"
